### ISSUE TITLE
front-end fails to run with Feed returned error

### ISSUE THREAD

**Issue by harryleesan** [ThoughtWorksInc/infra-problem#8]
The front-end throws an error when calling the newsfeed api.

```
frontend    | 21:08:26.409 [worker-3] ERROR front-end.core - GET /
frontend    | java.lang.Exception: Feed returned error
frontend    |   at front_end.data$handle_response.invokeStatic(data.clj:28)
frontend    |   at front_end.data$handle_response.invoke(data.clj:24)
frontend    |   at front_end.data$handle_news_response.invokeStatic(data.clj:60)
frontend    |   at front_end.data$handle_news_response.invoke(data.clj:58)
frontend    |   at front_end.core$index.invokeStatic(core.clj:18)
frontend    |   at front_end.core$index.invoke(core.clj:14)
frontend    |   at front_end.core$fn__3659.invokeStatic(core.clj:30)
frontend    |   at front_end.core$fn__3659.invoke(core.clj:30)
frontend    |   at compojure.core$wrap_response$fn__1919.invoke(core.clj:158)
frontend    |   at compojure.core$wrap_route_middleware$fn__1903.invoke(core.clj:128)
frontend    |   at compojure.core$wrap_route_info$fn__1908.invoke(core.clj:137)
frontend    |   at compojure.core$wrap_route_matches$fn__1912.invoke(core.clj:146)
frontend    |   at compojure.core$routing$fn__1927.invoke(core.clj:185)
frontend    |   at clojure.core$some.invokeStatic(core.clj:2701)
frontend    |   at clojure.core$some.invoke(core.clj:2692)
frontend    |   at compojure.core$routing.invokeStatic(core.clj:185)
frontend    |   at compojure.core$routing.doInvoke(core.clj:182)
frontend    |   at clojure.lang.RestFn.applyTo(RestFn.java:139)
frontend    |   at clojure.core$apply.invokeStatic(core.clj:667)
frontend    |   at clojure.core$apply.invoke(core.clj:660)
frontend    |   at compojure.core$routes$fn__1931.invoke(core.clj:192)
frontend    |   at common_utils.middleware$correlation_id_middleware$fn__2020.invoke(middleware.clj:12)
frontend    |   at front_end.core$wrap_exception_handling$fn__3652.invoke(core.clj:23)
frontend    |   at ring.middleware.reload$wrap_reload$fn__3473.invoke(reload.clj:22)
frontend    |   at clojure.lang.Var.invoke(Var.java:384)
frontend    |   at org.httpkit.server.HttpHandler.run(RingHandler.java:115)
frontend    |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
frontend    |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
frontend    |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
frontend    |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
frontend    |   at java.lang.Thread.run(Thread.java:748)
frontend    | Caused by: org.httpkit.client.TimeoutException: idle timeout: 1000ms
frontend    |   at org.httpkit.client.HttpClient.clearTimeout(HttpClient.java:131)
frontend    |   at org.httpkit.client.HttpClient.run(HttpClient.java:496)
frontend    |   ... 1 common frames omitted
```

**Comment by bhargavamin** [comment]
Facing the same issue.
